<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-VAQKFJ2" failures="0" tests="4" name="Test" time="24.775" errors="0" timestamp="15 Apr 2024 09:57:25 GMT">
  <testcase classname="qa.tests.TC_02_VerifyUserAbleToPlaceTheOrder" name="verifyUserAbleToPlaceTheOrder" time="3.187"/>
  <testcase classname="qa.tests.TC_02_VerifyUserAbleToPlaceTheOrder" name="verifyUserAbleToPlaceTheOrder" time="3.475"/>
  <testcase classname="qa.tests.TC_01_VerifyUserAbleToLoginIntoApplication" name="verifyUserAbleToLoginIntoApplication" time="0.674"/>
  <testcase classname="qa.tests.TC_01_VerifyUserAbleToLoginIntoApplication" name="verifyUserAbleToLoginIntoApplication" time="0.837"/>
  <testcase classname="qa.tests.TC_01_VerifyUserAbleToLoginIntoApplication" name="verifyWhetherApplicationProvidAlertMessageWithWrongUserCredentials" time="0.0">
    <ignored/>
  </testcase> <!-- verifyWhetherApplicationProvidAlertMessageWithWrongUserCredentials -->
</testsuite> <!-- Test -->
